### ISSUE TITLE
Hỏi về cách chạy dự án

### ISSUE THREAD

**Issue by TanhGL** [npv2k1/ktltweb#3]
chào bác, em đã thử chạy file docker mà k biết thiếu bước cấu hình như nào. mong bác chỉ dẫn ạ. Em xin cảm ơn

**Comment by npv2k1** [comment]
Bạn clone source về rồi chạy lệnh `docker-compose up` là được.

**Comment by TanhGL** [comment]
dạ bác cho e xin link fb hoặc zalo trao đổi được k ạ. Em xin cảm ơn. Zalo của em là 0989801720

**Comment by npv2k1** [comment]
Add facebook nha https://www.facebook.com/pvnpvnpvn/
